services:
  server:
    build: ./server
    container_name: ai-chat-server-container

    ports:
      - "5000:5000"

    env_file:
      - ./server/.env

  client:
    build: ./client
    container_name: ai-chat-client-container

    ports:
      - "5173:5173"

    depends_on:
      - server