name: AI Chat App CI

on:
  push:
    branches:
      - main

jobs:
  frontend: 
    run-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install 

      - name: Run ESLint
        run: npm run lint

      - name: Build Project 
        run: npm run build